// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Expenses;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext( typeof( ExpensesDbContext ) )]
    [Migration( "20250610145539_ExpenseTables" )]
    partial class ExpenseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel( ModelBuilder modelBuilder )
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation( "ProductVersion", "9.0.5" )
                .HasAnnotation( "Relational:MaxIdentifierLength", 128 );

            SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder );

            modelBuilder.Entity( "Domain.Expenses.Expense", b =>
                {
                    b.Property<Guid>( "Id" )
                        .ValueGeneratedOnAdd()
                        .HasColumnType( "uniqueidentifier" );

                    b.Property<DateTimeOffset>( "CreationDate" )
                        .HasColumnType( "datetime" );

                    b.Property<string>( "Description" )
                        .IsRequired()
                        .HasMaxLength( 128 )
                        .HasColumnType( "nvarchar(128)" );

                    b.Property<decimal>( "Value" )
                        .HasColumnType( "decimal(18,2)" );

                    b.HasKey( "Id" );

                    b.ToTable( "Expenses" );
                } );
#pragma warning restore 612, 618
        }
    }
}
