// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Incomes;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext( typeof( IncomesDbContext ) )]
    partial class IncomesDbContextModelSnapshot: ModelSnapshot
    {
        protected override void BuildModel( ModelBuilder modelBuilder )
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation( "ProductVersion", "9.0.5" )
                .HasAnnotation( "Relational:MaxIdentifierLength", 128 );

            SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder );

            modelBuilder.Entity( "Domain.Incomes.Income", b =>
                {
                    b.Property<Guid>( "Id" )
                        .ValueGeneratedOnAdd()
                        .HasColumnType( "uniqueidentifier" );

                    b.Property<DateTimeOffset>( "CreationDate" )
                        .HasColumnType( "datetimeoffset" );

                    b.Property<string>( "Description" )
                        .IsRequired()
                        .HasMaxLength( 128 )
                        .HasColumnType( "nvarchar(128)" );

                    b.Property<string>( "Source" )
                        .IsRequired()
                        .HasMaxLength( 128 )
                        .HasColumnType( "nvarchar(128)" );

                    b.Property<decimal>( "Value" )
                        .HasColumnType( "decimal(18,2)" );

                    b.Property<decimal>( "Withholding" )
                        .HasColumnType( "decimal(18,2)" );

                    b.HasKey( "Id" );

                    b.ToTable( "Incomes" );
                } );
#pragma warning restore 612, 618
        }
    }
}
