// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Notifications;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext( typeof( NotificationsDbContext ) )]
    partial class NotificationsDbContextModelSnapshot: ModelSnapshot
    {
        protected override void BuildModel( ModelBuilder modelBuilder )
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation( "ProductVersion", "9.0.5" )
                .HasAnnotation( "Relational:MaxIdentifierLength", 128 );

            SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder );

            modelBuilder.Entity( "Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>( "Id" )
                        .ValueGeneratedOnAdd()
                        .HasColumnType( "uniqueidentifier" );

                    b.Property<DateTimeOffset>( "CreationDate" )
                        .HasColumnType( "datetimeoffset" );

                    b.Property<DateTimeOffset>( "DateToSend" )
                        .HasColumnType( "datetimeoffset" );

                    b.Property<string>( "Description" )
                        .IsRequired()
                        .HasMaxLength( 128 )
                        .HasColumnType( "nvarchar(128)" );

                    b.Property<string>( "Email" )
                        .HasMaxLength( 128 )
                        .HasColumnType( "nvarchar(128)" );

                    b.Property<bool>( "Enable" )
                        .HasColumnType( "bit" );

                    b.Property<int>( "Frequency" )
                        .HasColumnType( "int" );

                    b.Property<int>( "HourToSend" )
                        .HasColumnType( "int" );

                    b.Property<int>( "Method" )
                        .HasColumnType( "int" );

                    b.Property<Guid?>( "PaymentId" )
                        .HasColumnType( "uniqueidentifier" );

                    b.Property<string>( "PhoneNumber" )
                        .HasMaxLength( 32 )
                        .HasColumnType( "nvarchar(32)" );

                    b.Property<bool>( "Repeatable" )
                        .HasColumnType( "bit" );

                    b.HasKey( "Id" );

                    b.ToTable( "Notifications" );
                } );
#pragma warning restore 612, 618
        }
    }
}
