name: CICD-PROCS

on:
  push:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    permissions:
        id-token: write
        contents: write
  
    steps:
    - uses: actions/checkout@v4
    
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOWS_SECRET }}     
        INITIAL_VERSION: 1.0.2
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}

  package-and-publish-contracts:
    runs-on: ubuntu-latest
    needs: generate-version

    permissions:
        id-token: write
        contents: write
  
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.WORKFLOWS_SECRET }} 
        
    - name: Pack
      run: | 
        dotnet pack . \
        --configuration Release \
        -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
        -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/Moneyfy.Persistence \
        -o packages

    - name: Publish
      run: dotnet nuget push packages/*.nupkg
